### ISSUE TITLE
Feature request: Set defaults in config

### ISSUE THREAD

**Issue by skttl** [skybrud/Skybrud.Umbraco.GridData#16]
How about an ability to set defaults in web.config?

like
<add key="Skybrud.Umbraco.GridData.DefaultPropertyAlias" value="bodyText"/>
<add key="Skybrud.Umbraco.GridData.DefaultFramework" value="bootstrap3"/>

**Comment by abjerner** [comment]
@skttl did you perhaps miss a screenshot or snippet?

If you can provide some more details, I'd be happy to look into it ;)

**Comment by skttl** [comment]
sorry, like
`<add key="Skybrud.Umbraco.GridData.DefaultFramework" value="bootstrap3"/>
<add key="Skybrud.Umbraco.GridData.DefaultPropertyAlias" value="bodyText"/>`

**Comment by ronaldbarendse** [comment]
I would keep it the same as the core [Umbraco grid](https://github.com/umbraco/Umbraco-CMS/blob/5397f2c53acbdeb0805e1fe39fda938f571d295a/src/Umbraco.Web/GridTemplateExtensions.cs#L20), so no default property alias and `bootstrap3` as the default framework.

**Comment by ronaldbarendse** [comment]
Oh, I see these defaults are already defined as constants in `TypedGridExtensionMethods` and used in the optional arguments (in part: for the property alias old-school overloads are used).

Since [optional argument values must be constants](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#optional-arguments), changing these to settings would require changing the API, e.g. passing `null` as value would use the default setting.

**Comment by abjerner** [comment]
As Ronald writes, this works the same way as Umbraco's `GetGridHtml` extension method does. I think that is how it works the best.
