### ISSUE TITLE
Question about GetSearchableText function

### ISSUE THREAD

**Issue by AndersBrohus** [skybrud/Skybrud.Umbraco.GridData#25]
Hi :)

Hope it's okay to make a question because maybe it's also an issue ;)

Currently working on a project where we use your package to make the grid searchable :)

But we are facing a little problem because when the following code does not make any new lines, it's simply puts the text together with no spaces in between.

`<strong>Billettelefonens åbningstider</strong><br /><strong>Tlf. XX XX XX XX</strong>`

The output i get from the GetSearchableText function is this

`Billettelefonens åbningstiderTlf. XX XX XX XX`

But i hoped there would be a space between the two words like this "åbningstider Tlf."... :)

Looking forward for your answer :)

**Comment by abjerner** [comment]
Hi Anders and thanks for reporting 👍 

It does indeed look like an issue. I'd imagine it's because the HTML isn't generated by the RTE, and therefore not with paragraphs and new lines. Am I right?

The current implementation just strips all HTML tags from the value. Technically each HTML tag is replaced with an empty string, where it should probably be replaced by a single space or new line (`\n`) instead. The code for that part is here:

https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/master/src/Skybrud.Umbraco.GridData/Values/GridControlHtmlValue.cs#L30

I'll look into fixing and and pushing a new release ;)

**Comment by AndersBrohus** [comment]
Because it's not paragraphs simply wanted a new line not an new paragraph and when you use SHIFT + Enter the RTE is making an "<br/>" 😄 

It could be really great with an new release! 👍 😄

**Comment by abjerner** [comment]
Better late than never. This is now fixed in [**v2.0.7**](https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v2.0.7) :tada:
