### ISSUE TITLE
Umbraco 8.2.2 upgrade 

### ISSUE THREAD

**Issue by brvaland** [skybrud/Skybrud.Umbraco.GridData#31]
Hi Anders

We have upgraded to Umbraco v8.2.2 from 8.1.5. When reading grid row label in view, it is returned null. I have checked datatype under setting and see label is setup in row configuration.

Can you please advise if there is any breaking changes with 8.2.2 ?

**Comment by abjerner** [comment]
Hi @brvaland,

I had a 8.1.4 test solution already running, so I tried upgrading to 8.2.2, and then also to 8.3.0 after that.

It seems that Umbraco is no longer adding the `label` property to the JSON of the rows. I'm not sure in which release of Umbraco this changed, or whether the change was intentional or not (I had a quick lot at the change list, but I couldn't spot anything related). So my advice would be to raise the issue on Umbraco's issue tracker as well 😉

**Comment by abjerner** [comment]
Hey @brvaland,

I haven't heard back from you, so I'm therefore closing this issue.
