### ISSUE TITLE
Release v3.0.0

### ISSUE THREAD

**Issue by skttl** [skybrud/Skybrud.Umbraco.GridData#32]
Is there anything missing before 3.0.0 can be released?

Trying to make a nuget package (internal) depend on this, but I can't because it's a prerelease :)

**Comment by abjerner** [comment]
Hi Søren,

I guess it depends a bit on how you look at it. To my knowledge there are no outstanding issues that prevent the current code to be released as stable, so in that regard, I could push a stable release.

On the other hand, my purpose of labeling our releases as beta is usually that I have some planned changes, that I would rather make during the betas so they don't become breaking changes in the stable releases.

Here are some of the changes I've been thinking about:

- **Introducing interfaces for the various parts of the grid** 
  Eg. so the grid model would be returned as `IGridDataModel` instead of `GridDataModel`, sections as `IGridSection` instead of `GridSection` and so forth, which would provide some extra flexibility.

  If a factory concept is introduced as well, it would also allow developers to provide their own models instead of the ones that come with the package. Interfaces would also allow for writable models (eg. generating or modifying the various parts of the grid by code), which is one of the features that is occasionally requested.

  I'm not entirely sure about the details yet, but introducing interfaces would solve a number of different problems.

- **Improving the use of generics**  
  The current use of generics could be improved. Right now when you iterate over the the controls of an area, you get instances of `GridControl` which it self is not generic.

  Right know you can use `GridContext` to get an instance of the generic `GridControlWrapper<TValue, TConfig>`. I think iterating over the controls, you should get the generic instance right away.

- **Indexing the grid**  
  With DTGE and other packages, it's becoming more and more likely that the value of grid controls are based on element types. With the current there really isn't anything to help addressing this, so I'd like to find some solution for this as well.

- **Other stuff...**

Ideally I would have been able to look at some of these issues already, but I've been super busy for a while now, and therefore not able to look into these issues yet. This has therefore also made me think about releasing a stable `v3.0.0` now, and address these issues for a `v3.1.0` instead. But then there will for sure be breaking changes between `v3.0.0` and `v3.1.0`.

There are pros and cons going either way, and I haven't settled on which way to go yet. This is typically also one of the parts I don't receive a lot (if any) feedback on, so hearing your thoughts would be helpful 😉

**Comment by hifi-phil** [comment]
Hi Anders, we are releasing our Yuzu framework shortly and we use this package as a dependency which is forcing a few of the packages to be pre-release. Any news on releasing this?

Would really like to show you around what we've done with Yuzu if you have a spare half an hour?

**Comment by abjerner** [comment]
Things don't always go according to plan. I had hoped that I by now would have had the time to make the changes that I described in my comment from back in November.

I still plan on making those changes, but as I'm not sure when I'll have the time to do so, I've pushed the first stable release for Umbraco 8:

https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v3.0.0

There are only a few small changes between `v3.0.0-beta004` and `v3.0.0`, so updating the package via NuGet should do the trick without any breaking changes 😉

**Comment by hifi-phil** [comment]
Thanks, Anders
