### ISSUE TITLE
Umbraco 9 support

### ISSUE THREAD

**Issue by skttl** [skybrud/Skybrud.Umbraco.GridData#38]
Just want to touch base on this - do you have any plans? I envision having to upgrade a few v8 solutions using grid and this wonderful package, and wondering if you have any plans regarding v9 support?

Would be happy to help with porting :)

**Comment by abjerner** [comment]
Hi Søren

I did play around with it recently just for the fun of it, and made as much progress that it now builds against beta 3. You can see my progress here:

https://github.com/skybrud/Skybrud.Umbraco.GridData/tree/dev/v9

I had to comment our all the logic around `HtmlHelper`. I haven't had much time to play around with ASP.NET Core in general, so I don't know how to do the same for ASP.NET Core. At least not yet. But then again, this is mostly "nice to have".

The main logic about making the grid strongly typed should have been converted already. Like I wrote, it builds - but I haven't really had the time to test it beyond that yet.

I've also introduced some new concepts:

- **Factory**  
  Instead of each model being responsible for initializing it self, the package is now using a [factory pattern](https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/dev/v9/src/Skybrud.Umbraco.GridData/Factories/DefaultGridFactory.cs) instead. IMO this makes all the parsing and the use of DI a lot cleaner.
  
  It was my plan to have included this for Umbraco 8 as well, but as I didn't have the time to wrap it up back then, it didn't make the cut. And adding it later would become too much of a breaking change. Luckily I could use most of my progress for the Umbraco 9 version.

- **Generics**  
Earlier versions had the generic `GridControlWrapper` class, which I've always felt was a bit clumsy in the way that you had to make an extra call to get the control wrapper instance. Now the factory will automatically create `GridControl<TValue>` and `GridEditor<TConfig>` (can't remember whether I finished all of that yet).

- **WriteSearchableText**  
Earlier versions also had a `GetSearchableText` method for a lot of the models making up the grid. As calls to that method would propagate down the grid, it would involve quite a lot of string concatenation. For Umbraco 9, the method is still there, but the primary method is now `WriteSearchableText`, which has a `TextWriter` as parameter. This means that if you call either `GetSearchableText` or `WriteSearchableText` on the main grid model, only a single `StringBuilder` and `TextWriter` will be created.

- **Elements**
In Umbraco 8 we used our own [Skybrud.Umbraco.Elements package](https://github.com/skybrud/Skybrud.Umbraco.Elements) instead of DTGE. But with either package there wasn't a straight forward way to get a textual representation of the wrapped `IPublishedElement`. With the package for Umbraco 9, each control (or it's value implementation) can now ask the [GridContext instance](https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/dev/v9/src/Skybrud.Umbraco.GridData/GridContext.cs#L29), which again will ask all the added grid converters until one of them recognized the respective value classes.

  I did start on a [Skybrud.Umbraco.GridData.Dtge](https://github.com/skybrud/Skybrud.Umbraco.GridData.Dtge) for Umbraco 8, but never got around finishing as we haven't used DTGE our selves. But I'd reckon it could make sense creating a package like this for Umbraco 9 that brings GridData and DTGE together.

**Comment by drbldgtl** [comment]
Hi, just curious if there are plans to further develop the v9 solution beyond alpha?

**Comment by abjerner** [comment]
Hi everyone and sorry for the lack of reply,

I haven't needed this package for Umbraco 9 my self, which unfortunately also has meant that I haven't really gotten around to releasing a stable release for Umbraco 9 ... until now:

https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v4.0.0

This release doesn't really change any code compared to v4.0.0-alpha002, but instead changes some of the package information.
