### ISSUE TITLE
Make compatible with Umbraco 7.3

### ISSUE THREAD

**Issue by jbreuer** [skybrud/Skybrud.Umbraco.GridData#5]
In Umbraco 7.3 has it's own GridValueConverter: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/PropertyEditors/ValueConverters/GridValueConverter.cs. This package probably needs to be updated in order to make it compatible.

More info: http://issues.umbraco.org/issue/U4-6148#comment=67-21169

**Comment by jbreuer** [comment]
Umbraco will also crash if there are 2 converters so this converter should disable the default converter of Umbraco 7.3. That can be done like this: https://github.com/jbreuer/Hybrid-Framework-for-Umbraco-v7-Best-Practises/blob/master/Umbraco.Extensions/Events/UmbracoEvents.cs#L63

**Comment by abjerner** [comment]
Hi Jeroen,

I have now committed a fix that does somewhat the same as Umbraco's new `GridValueConverter`. 

Since I now use some of the new logic in 7.3-beta2, the package is now build against 7.3-beta2 rather than 7.2.0 as before. This means that I will have to look into whether I need to maintain one version for 7.2.x and another version for 7.3.x, or whether I can just make a check in my code so the new logic is only executed for 7.3. When I have time to look into that, I'll make a new release ;)

Btw - do you have any examples where Umbraco will crash if there are multiple property value converters for the same alias? If I install my package in a new 7.3-beta2 installation, everything works fine - meaning that calling `Model.Content.GetPropertyValue("content")` will return an instance of `GridDataModel` from my package, and I don't experience any crashes.
